# セクション3 : Numpy, 特にndarrayを理解

In [1]:
import numpy as np

In [2]:
# list
arr1 = [1, 3 ,5]
arr2 = [2, 4, 6]
arr1

[1, 3, 5]

In [3]:
# numpy ndarray
np_arr1 = np.array(arr1)
np_arr2 = np.array(arr2)
np_arr1

array([1, 3, 5])

In [4]:
print(type(arr1))
print(type(np_arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
np_arr1.dtype

dtype('int64')

In [6]:
arr1.dtype # listはない

AttributeError: 'list' object has no attribute 'dtype'

In [7]:
np_arr1 * 2 # 各要素が2倍される

array([ 2,  6, 10])

In [8]:
arr1 * 2 # listが連結される

[1, 3, 5, 1, 3, 5]

In [9]:
np_arr1 + np_arr2 # 各要素が足される

array([ 3,  7, 11])

In [10]:
arr1 + arr2 # list連結

[1, 3, 5, 2, 4, 6]

In [11]:
np_arr1 * np_arr2 # 各要素が掛け算される

array([ 2, 12, 30])

In [12]:
arr1 * arr2 # error

TypeError: can't multiply sequence by non-int of type 'list'

Numpy ndarrayの最大値、最小値、平均、合計

In [13]:
np_arr1.max()

np.int64(5)

In [14]:
np_arr1.min()

np.int64(1)

In [16]:
np_arr1.mean()

np.float64(3.0)

In [17]:
np_arr1.sum()

np.int64(9)

分散と標準偏差

In [18]:
np_arr1.var()

np.float64(2.6666666666666665)

In [19]:
np_arr1.std()

np.float64(1.632993161855452)

ファンシーインデックス

In [20]:
arr3 = [[0, 100], [200, 300]]
np_arr3 = np.array(arr3)

In [23]:
np_arr3[0][1]

np.int64(100)

In [24]:
np_arr3[0, 1] # ファンシーインデックス(listはerrorになる)

np.int64(100)

In [26]:
arr4 = [0, [100, 200], [300, 400, 500]]
np.array(arr4) # error(形状をそろえないといけない)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [27]:
# 形状がそろっていないlistはdtypeをobjectにするとnumpy配列にできる
arr5 = [[0, [1, 2]], [3, [4, 5]]]
np.array(arr5, dtype=object)

array([[0, list([1, 2])],
       [3, list([4, 5])]], dtype=object)

In [28]:
arr6 = [[0, 1, 2.0], [3, 4, 5]]
np_arr6 = np.array(arr6)
np_arr6


array([[0., 1., 2.],
       [3., 4., 5.]])

In [29]:
np_arr6.dtype

dtype('float64')

In [32]:
np_arr6 = np_arr6.astype(int) # dtype変換
np_arr6.dtype

dtype('int64')

In [33]:
arr7 = [[0, 1, '2'], [3, 4, 5]]
np_arr7 = np.array(arr7)
np_arr7.dtype # <U21になる(UはUnicode)

dtype('<U21')

In [37]:
np_arr7_1 = np_arr7.astype(int) # int変換
np_arr7_1

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
np_arr7_2 = np_arr7.astype(object) # object変換
np_arr7_2 # numpyではstrをobjectであつかう

array([['0', '1', '2'],
       ['3', '4', '5']], dtype=object)

`np.arange(start, stop, step)` : 範囲と数値の幅から作成(array range)

In [41]:
np.arange(8) # defaultではstart=0, step=1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
np.arange(0, 8, 1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
np.arange(-5, 5, 2)

array([-5, -3, -1,  1,  3])

In [44]:
np.arange(0, 6.1, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

`np.linspace(start, stop, size)` : 範囲と生成数から作成

In [45]:
np.linspace(8) # error

TypeError: linspace() missing 1 required positional argument: 'stop'

In [46]:
np.linspace(0, 8) # sizeのdefaultは50

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [47]:
np.linspace(0, 5, 10) # stop含まれる(arangeは含まれない)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [48]:
np.linspace(0, 5, 10, endpoint=False) # こうするとstop含まない

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

`np.random.randint(low, high, size)` : 整数

In [49]:
np.random.randint(10, 20)

10

In [50]:
np.random.randint(10, 30,5)

array([12, 24, 26, 21, 23], dtype=int32)

In [51]:
np.random.randint(10, 30, (3, 4))

array([[12, 20, 12, 29],
       [23, 11, 23, 14],
       [29, 11, 27, 14]], dtype=int32)

In [52]:
np.random.randint(10, 50, (3, 4, 2))

array([[[19, 16],
        [38, 45],
        [18, 35],
        [20, 44]],

       [[36, 26],
        [25, 38],
        [32, 13],
        [27, 20]],

       [[18, 14],
        [36, 30],
        [30, 25],
        [43, 44]]], dtype=int32)

シード指定

In [54]:
np.random.seed(17) # セル内でのみ有効
np.random.randint(1, 100)

16

`np.random.rand(5)` : 0以上1未満

In [55]:
np.random.rand(5)

array([0.84423384, 0.88886482, 0.80682133, 0.41022325, 0.10299386])

In [56]:
np.random.rand(3, 4)

array([[0.219501  , 0.62975761, 0.85992408, 0.04127257],
       [0.74256622, 0.57041736, 0.03431319, 0.21551321],
       [0.48756902, 0.27270586, 0.11906343, 0.29963408]])

`np.random.uniform(low, high, size)` : 範囲と生成数を指定, 連続一様分布に基づく

In [57]:
np.random.uniform(2, 8, 100).mean()

np.float64(4.9682294080483675)

`np.random.choice(array, size)` : Listの値をランダムに選択

In [58]:
l = [16, 87, 233]
np.random.choice(l, 5)

array([233, 233,  16,  16, 233])

In [59]:
np.random.choice(l, (2, 3))

array([[ 87,  87, 233],
       [ 87,  16,  16]])

`np.random.randn(size)` : 平均0, 標準偏差1の正規分布に基づく数列

In [61]:
print(np.random.randn(1000).mean())
print(np.random.randn(1000).std())

0.011744963989798766
1.0266722679979292


`np.random.normal(average, standard_deviation, size)` : 平均と標準偏差を指定した正規分布に基づく数列

In [62]:
np.random.normal(50, 1, 10)

array([49.36525637, 51.12797304, 49.02833921, 50.78361136, 50.54968395,
       49.93377107, 50.97184643, 48.52433133, 48.89057947, 51.91432854])

In [63]:
print(np.random.normal(10, 5, 1000).mean())
print(np.random.normal(10, 5, 1000).std())

9.988258842372831
5.107084886791089


In [64]:
np_arr = np.random.rand(2, 3, 4)
np_arr

array([[[0.04775194, 0.67346396, 0.80098011, 0.37003964],
        [0.59145198, 0.18401067, 0.04020466, 0.57311568],
        [0.70489616, 0.48727359, 0.0794815 , 0.82966267]],

       [[0.15511438, 0.05796835, 0.51162333, 0.23378201],
        [0.2627839 , 0.76551328, 0.93447765, 0.68129399],
        [0.12880476, 0.97206618, 0.72648815, 0.04645596]]])

In [65]:
# 次元の確認
np_arr.ndim

3

In [66]:
# 形状の確認
np_arr.shape

(2, 3, 4)

In [67]:
# サイズ(要素数)の確認
np_arr.size

24

In [69]:
# 形状の変換
np_arr.reshape(4, 6)

array([[0.04775194, 0.67346396, 0.80098011, 0.37003964, 0.59145198,
        0.18401067],
       [0.04020466, 0.57311568, 0.70489616, 0.48727359, 0.0794815 ,
        0.82966267],
       [0.15511438, 0.05796835, 0.51162333, 0.23378201, 0.2627839 ,
        0.76551328],
       [0.93447765, 0.68129399, 0.12880476, 0.97206618, 0.72648815,
        0.04645596]])

In [70]:
np_arr.reshape(1, -1)

array([[0.04775194, 0.67346396, 0.80098011, 0.37003964, 0.59145198,
        0.18401067, 0.04020466, 0.57311568, 0.70489616, 0.48727359,
        0.0794815 , 0.82966267, 0.15511438, 0.05796835, 0.51162333,
        0.23378201, 0.2627839 , 0.76551328, 0.93447765, 0.68129399,
        0.12880476, 0.97206618, 0.72648815, 0.04645596]])

In [71]:
np_arr.reshape(-1) # 1次元配列

array([0.04775194, 0.67346396, 0.80098011, 0.37003964, 0.59145198,
       0.18401067, 0.04020466, 0.57311568, 0.70489616, 0.48727359,
       0.0794815 , 0.82966267, 0.15511438, 0.05796835, 0.51162333,
       0.23378201, 0.2627839 , 0.76551328, 0.93447765, 0.68129399,
       0.12880476, 0.97206618, 0.72648815, 0.04645596])

In [72]:
np_arr.ravel() # 1次元配列に変換(reshape(-1)と同じ)

array([0.04775194, 0.67346396, 0.80098011, 0.37003964, 0.59145198,
       0.18401067, 0.04020466, 0.57311568, 0.70489616, 0.48727359,
       0.0794815 , 0.82966267, 0.15511438, 0.05796835, 0.51162333,
       0.23378201, 0.2627839 , 0.76551328, 0.93447765, 0.68129399,
       0.12880476, 0.97206618, 0.72648815, 0.04645596])

In [73]:
np_arr.flatten() # これも1次元配列に変換

array([0.04775194, 0.67346396, 0.80098011, 0.37003964, 0.59145198,
       0.18401067, 0.04020466, 0.57311568, 0.70489616, 0.48727359,
       0.0794815 , 0.82966267, 0.15511438, 0.05796835, 0.51162333,
       0.23378201, 0.2627839 , 0.76551328, 0.93447765, 0.68129399,
       0.12880476, 0.97206618, 0.72648815, 0.04645596])

flattenとravelの違いは以下
- flattenの場合はメモリ上にコピーを作成
- ravelはコピー作成しない

In [77]:
np_arr.flatten()[0] = 99 # 変わらない
np_arr

array([[[9.90000000e+01, 6.73463958e-01, 8.00980109e-01, 3.70039639e-01],
        [5.91451985e-01, 1.84010672e-01, 4.02046598e-02, 5.73115676e-01],
        [7.04896158e-01, 4.87273592e-01, 7.94814963e-02, 8.29662670e-01]],

       [[1.55114379e-01, 5.79683547e-02, 5.11623326e-01, 2.33782005e-01],
        [2.62783898e-01, 7.65513285e-01, 9.34477655e-01, 6.81293986e-01],
        [1.28804763e-01, 9.72066181e-01, 7.26488148e-01, 4.64559596e-02]]])

In [78]:
np_arr.ravel()[0] = 99 # 変わる
np_arr

array([[[9.90000000e+01, 6.73463958e-01, 8.00980109e-01, 3.70039639e-01],
        [5.91451985e-01, 1.84010672e-01, 4.02046598e-02, 5.73115676e-01],
        [7.04896158e-01, 4.87273592e-01, 7.94814963e-02, 8.29662670e-01]],

       [[1.55114379e-01, 5.79683547e-02, 5.11623326e-01, 2.33782005e-01],
        [2.62783898e-01, 7.65513285e-01, 9.34477655e-01, 6.81293986e-01],
        [1.28804763e-01, 9.72066181e-01, 7.26488148e-01, 4.64559596e-02]]])

In [79]:
arr = [[2, 4, 8], [3, 9, 2]]
np_arr = np.array(arr)
np_arr

array([[2, 4, 8],
       [3, 9, 2]])

In [80]:
# ブロードキャスト
print(np_arr + 1000)
print(np_arr * 2)
print(np_arr % 3)
print(np_arr // 5)

[[1002 1004 1008]
 [1003 1009 1002]]
[[ 4  8 16]
 [ 6 18  4]]
[[2 1 2]
 [0 0 2]]
[[0 0 1]
 [0 1 0]]


In [81]:
np_arr + np_arr

array([[ 4,  8, 16],
       [ 6, 18,  4]])

In [82]:
np_arr + [1000, 2000, 3000] # 形状の異なるnumpy配列とlistの演算

array([[1002, 2004, 3008],
       [1003, 2009, 3002]])

In [83]:
np_arr + [[1000], [2000]]

array([[1002, 1004, 1008],
       [2003, 2009, 2002]])

In [84]:
np_arr.sum()

np.int64(28)

In [85]:
np_arr.sum(axis=0)

array([ 5, 13, 10])

In [86]:
np_arr.sum(axis=1)

array([14, 14])

In [87]:
np.power(np_arr, 2) # 乗数

array([[ 4, 16, 64],
       [ 9, 81,  4]])

In [88]:
np.sqrt(np_arr) # 平方根

array([[1.41421356, 2.        , 2.82842712],
       [1.73205081, 3.        , 1.41421356]])

In [89]:
np.sin(np_arr) # sin関数

array([[ 0.90929743, -0.7568025 ,  0.98935825],
       [ 0.14112001,  0.41211849,  0.90929743]])

In [91]:
print(np.floor(np.sqrt(np_arr))) # 切り下げ
print(np.ceil(np.sqrt(np_arr))) # 切り上げ
print(np.round(np.sqrt(np_arr))) # 四捨五入
print(np.round(np.sqrt(np_arr), 5)) # 四捨五入する桁を指定

[[1. 2. 2.]
 [1. 3. 1.]]
[[2. 2. 3.]
 [2. 3. 2.]]
[[1. 2. 3.]
 [2. 3. 1.]]
[[1.41421 2.      2.82843]
 [1.73205 3.      1.41421]]


In [92]:
np.abs(np_arr - 10) # 絶対値

array([[8, 6, 2],
       [7, 1, 8]])